[Interface]
PrivateKey = eOFocmEuYY1d46gynZmL0fYFiSx8qoF0t433dr4DQ2g=
Address = 10.7.0.5/32
MTU = 1420

[Peer]
PublicKey = itTtCRRcad/zZHcwssmblaimyP7qOqGizI4wdPA/sQE=
AllowedIPs = 10.7.0.1/32
Endpoint = 1.95.65.51:51820
PersistentKeepalive = 25
